### ISSUE TITLE
Keybinds not working

### ISSUE THREAD

**Issue by markubiak** [Gigadoc2/i3-cinnamon#2]
I know I'm overlooking something really simple here, but this is bugging me quite a bit.

I'm trying to get my custom keybinds back.  Cinnamon handled volume and brightness beautifully, but i3-cinnamon does not handle either of these, even when the keybind manager is open.  I don't know if this is intentional, a bug, or me being stupid but I'm looking for a solution regardless of the source of the problem.

**Comment by Gigadoc2** [comment]
Actually I'm having a similar issue myself, keybindings just stopped working for me entirely when using cinnamon or gnome. Maybe this is related, are keybindings working within a normal Cinnamon session?

Also, are only custom keybindings not working, or none at all?

> even when the keybind manager is open.

Does this mean the manager doesn't register your key presses, as in you cannot create new keybindings?

**Comment by markubiak** [comment]
Regular Cinnamon Desktop keybinds work fine, just not in i3. I can open the cinnamon keyboard settings but any keybinds I set don't work.

**Comment by Gigadoc2** [comment]
So, after some hours of experimenting I found the cause for this, but there is no easy solution unfortunatly.

Cinnamon splits its keybind-handling between the Window Manager (or rather, cinnamon-shell) and cinnamon-settings-daemon, cinnamon-shell recognizes the keypress and notifies cinnamon-settings-daemon via dbus, which reacts to the event. Since the i3-cinnamon session is not using cinnamon-shell, cinnamon-settings-daemon does not know when a key is pressed.

A proper solution might be to write a standalone "keybind-daemon" based on the code within cinnamon-shell, but I am not going to do this in the near future. So I'm afraid you have to use another program for keybindings, or configure them within i3.

**Comment by markubiak** [comment]
Thanks for the investigation, I've done them in the i3 config. I'll close the issue.
