### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by yuritoledo** [Gigadoc2/i3-cinnamon#5]

**Comment by Gigadoc2** [comment]
Well, these are just configuration files for cinnamon and the desktop manager so that you can select a Desktop called `i3 + Cinnamon` which is the cinnamon-session daemon but launching i3 instead of the cinnamon window manager.

There is also a PKGBUILD in here which is a thing for the Arch Linux package manager to build a package from these files, as unfortunately all these config files have to live in `/usr` and not `/etc`.
Technically that PKGBUILD should be in a different repository, but I was too lazy to do that.

Are you planning to use this on Arch or somehwere else?

BTW, I do no longer use this myself, because cinnamon-session does not work with wayland (and I now use sway instead of i3).

**Comment by yuritoledo** [comment]
I no longer use it, thank you :)
